apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r5ds2ydh2-python
  janus-idp.io/tekton: r5ds2ydh2-python
  backstage.io/kubernetes-id: r5ds2ydh2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r5ds2ydh2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
